# Generated by Django 3.0.5 on 2020-12-31 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('display_name', models.CharField(blank=True, max_length=256, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=256, null=True)),
                ('avatar', models.ImageField(default='default.png', upload_to='')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
