# Generated by Django 3.0.5 on 2020-12-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
