# Generated by Django 3.0.5 on 2020-12-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_auth', '0002_auto_20201231_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='avatar_url',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', upload_to='avatar/'),
        ),
    ]
