# Generated by Django 3.0.5 on 2021-01-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210119_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagegroup',
            name='name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
