# Generated by Django 3.0.5 on 2021-01-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystatus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
